pipeling is build

diff --git a/.github/workflows/smoke-test.yml b/.github/workflows/smoke-test.yml
--- a/.github/workflows/smoke-test.yml
+++ b/.github/workflows/smoke-test.yml
@@ -3,12 +3,62 @@ name : Smoke Testing For Infra and Network
 on: 
   workflow_call:
     
-    
 jobs:
-  working-job:
+  test:
     runs-on: ubuntu-latest
 
-
     steps:
-    - name: Echo messege
-      run: echo "Somke Test successfully"    
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::416394563192:role/github-action_deploy_policy
+          aws-region: us-east-1
+
+      - name: Upload smoke_test.py on AWS
+        run: |
+          aws s3 cp smoke_test.py
+          s3://416394563192-my-devops-script-109/smoke_test.py \
+          --region us-east-1
+
+
+      - name: Run smoke test on fleet
+        id: smoke
+        run: |
+          CMD_ID=$(aws ssm send-command \
+          --targets "Key=tag:App,Values=flask" \
+          --document-name "AWS-RunShellScript" \
+          --parameters '{"commands":[
+          "aws s3 cp s3://416394563192-my-devops-script-109/smoke_test.py  /tmpr/smoke_test.py",
+          "python3 /tmpr/smoke_test.py",
+          "rm /tmpr/smoke_test.py""
+          ]}' \
+          --query 'Command.CommandId' \
+          --output text \
+          --region us-east-1)
+
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT  
+
+      - name: show Result
+        run: |
+          sleep 30
+
+          aws ssm list-command-invocations \
+          --command-id "${{ steps.smoke.outputs.cmd_id }}"
+          --details \
+          --region us-east-1
+          --output test
+
+          FAILD=$(
+            aws ssm list-command-invocations \
+              --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+              --details \
+              --query "length(CommandInvocations[?Status=='Failed'])" \
+              --output text \
+              --region us-east-1 
+            )
+
+          [ "$FAILD" -gt 0 ] && \
+          echo "::error::smoke Check Faild on $FAILD instance(s)" && \
+          exit 1
+
+
+
